# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "default" # Skin color theme: "air", "aqua", "contrast", "dark", etc.

# Site Settings
locale                   : "en-US" # Language and region setting
rtl                      : # true, false (default) # Right-to-left layout (keep blank unless needed)
title                    : "Pascal SUNGU" # Title shown in browser tab
title_separator          : "-" # Used in title construction: "Pascal SUNGU - Page Title"
subtitle                 : "Academic and Professional Portfolio" # Optional tagline below title (can adjust later)
name                     : "Pascal SUNGU" # Used in author information
description              : "Applied mathematics, malaria modeling, and data-driven research in infectious diseases and vector control." # Shown in search engine previews
url                      : "https://pascal-sungu.github.io" # The full URL to your site
baseurl                  : "" # Leave blank for GitHub Pages using user/organization site (not a subfolder)
repository               : "Pascal-SUNGU/Pascal-SUNGU.github.io" # GitHub username/repository-name
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
breadcrumbs              : false # Optional breadcrumb navigation (enable if needed)
words_per_minute         : 200 # Used for estimating read time
enable_copy_code_button  : true # Adds a copy button to code blocks
copyright                : "Pascal SUNGU" # Shown in footer
copyright_url            : "https://pascal-sungu.github.io" # Link from the copyright
comments:
  provider: false # Disable comments for now (you can enable later with "giscus", "disqus", etc.)
  disqus:
    shortname: # Required if using Disqus
  discourse:
    server: # Required if using Discourse
  facebook:
    appid:
    num_posts: # 5 (default)
    colorscheme: # "light" or "dark"
  utterances:
    theme: # "github-light" (default), "github-dark"
    issue_term: # "pathname" (default)
  giscus:
    repo_id:
    category_name:
    category_id:
    discussion_term: # "pathname" (default)
    reactions_enabled: '1'
    theme: "light"
    strict: 0
    input_position: "bottom"
    emit_metadata: 0
    lang: "en"
    lazy: false
  staticman:
    branch: "master"
    endpoint: # Required if using Staticman

reCaptcha:
  siteKey:
  secret:

atom_feed:
  path: # blank (default) uses feed.xml
  hide: false

search: true # Enable search
search_full_content: false
search_provider: lunr

lunr:
  search_within_pages: false

algolia:
  application_id:
  index_name:
  search_only_api_key:
  powered_by: true

google:
  search_engine_id:
  instant_search: false

# SEO Related
google_site_verification:
bing_site_verification:
naver_site_verification:
yandex_site_verification:
baidu_site_verification:

# Social Sharing
twitter:
  username               : # ← (leave blank or add if you want)
facebook:
  username               : # ← (leave blank or add if you want)
  app_id                 : 
  publisher              : 
og_image                 : "/assets/images/social-default.png"  # ← optional image when sharing your site

# Social Profiles for Structured Data
social:
  type                   : Person
  name                   : Pascal SUNGU
  links: 
    - "https://github.com/Pascal-SUNGU"
    - "https://www.linkedin.com/in/pascal-sungu/"
    - "https://www.researchgate.net/profile/Pascal-Sungu-Ngoy"
    - "https://scholar.google.com/citations?hl=en&user=azCo2aoAAAAJ"

# Analytics
analytics:
  provider               : false # ← set to "google-gtag" later if using Google Analytics
  google:
    tracking_id          : 
    anonymize_ip         : false

# Site Author
author:
  name             : "Pascal SUNGU"
  avatar           : "/assets/images/pascal.jpg"  # ← Upload your image to this path
  bio              : "Personal academic and professional site of Pascal Sungu."
  location         : "Cameroon / Yaounde"
  email            : pascal.sungu@crid-cam.net
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Pascal-SUNGU"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/pascal-sungu/"
    - label: "ResearchGate"
      icon: "fas fa-fw fa-flask"
      url: "https://www.researchgate.net/profile/Pascal-Sungu-Ngoy"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?hl=en&user=azCo2aoAAAAJ"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Pascal-SUNGU"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/pascal-sungu/"
    - label: "ResearchGate"
      icon: "fas fa-fw fa-flask"
      url: "https://www.researchgate.net/profile/Pascal-Sungu-Ngoy"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?hl=en&user=azCo2aoAAAAJ"


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - minimal-mistakes-jekyll.gemspec
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs  # exclude docs folder from build
  - /test  # exclude test folder from build
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # options: nested, expanded, compact, compressed

# Outputting
permalink: /:categories/:title/
timezone: Africa/Yaounde  # <-- set your time zone here

# Pagination with jekyll-paginate
paginate: 5
paginate_path: /page:num/

# Pagination with jekyll-paginate-v2 (optional)
pagination:
  # enabled: true
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: ''
  trail:
    before: 2
    after: 2

# Plugins (previously called gems)
plugins:
  - jekyll-paginate         # basic blog pagination
  - jekyll-sitemap          # auto-generates sitemap.xml
  - jekyll-gist             # embed GitHub gists
  - jekyll-feed             # creates RSS feed
  - jekyll-include-cache    # speeds up includes

# Whitelisted plugins (safe mode for GitHub Pages)
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives (for tags and categories)
category_archive:
  type: liquid              # use Liquid templates (GitHub Pages–compatible)
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/

# Optional: enable if you want nicer permalinks for archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/

# HTML Compression (removes whitespace to reduce file size)
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults for blog posts
defaults:
  - scope:
      path: ""              # applies to all folders
      type: posts
    values:
      layout: single        # use the "single" layout
      author_profile: true  # show author info box
      read_time: true       # show estimated reading time
      comments:             # leave blank or set to true to enable later
      share: true           # enable social share buttons
      related: true         # show related posts
